<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit371cdee56355d31b8527ec2a465e1f7a
{
    public static $files = array (
        '35d1e42abf4d8c181ae544a92d8f3f6a' => __DIR__ . '/..' . '/kint-php/kint/Kint.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
